# Generated by Django 6.0.1 on 2026-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='cena',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
