# Generated by Django 6.0.1 on 2026-06-20 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Позиция корзины', 'verbose_name_plural': 'Позиции корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Покупатель'), ('ADMIN', 'Администратор'), ('MANAGER', 'Менеджер')], default='CUSTOMER', max_length=20, verbose_name='Роль')),
                ('favorite_category', models.CharField(blank=True, choices=[('rings', 'Кольца'), ('bracelets', 'Браслеты'), ('pendants', 'Подвески'), ('earrings', 'Серьги'), ('necklaces', 'Ожерелья')], max_length=20, null=True, verbose_name='Любимая категория украшений')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город доставки')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'myproject_profile',
            },
        ),
    ]
