# Generated by Django 6.0.3 on 2026-04-25 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorytovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('opisanie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proizvoditel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('country', models.CharField(max_length=400)),
                ('opisanie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('opisanie', models.TextField()),
                ('fotto', models.ImageField(upload_to='')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=40)),
                ('colnasklade', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tovars', to='myproject.categorytovar')),
                ('prozvoditel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prozvol', to='myproject.proizvoditel')),
            ],
        ),
        migrations.CreateModel(
            name='KorzinaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.korzina')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.tovar')),
            ],
        ),
    ]
